### ISSUE TITLE
can this project generate fidl file ?

### ISSUE THREAD

**Issue by hezhiye** [gemoc/franca-gen#1]
Hi:
    can this project generate fidl file ?
    what is the input ?

**Comment by dvojtise** [comment]
Hi

in short: no, it cannot generate fidl file.

the goal of the project is to provide several concrete implementations of protocols.
The protocol definition (ie. .fidl files) is the input.
In the initial version: the output will be java based implementation of protocols using WebSocket JSONRPC  (ie. allowing to define and implement protocols similar to LSP) 

next in the plan: 
- generation of the typescript version
- generation of the documentation (mainly plantuml based, but probably also html)
- generation of the JSON schema of the protocol (allowing to expose that the protocol exchanged conform to such schema)

later plan:
- support for more protocol implementations (ex: XMLRPC, or other variant we may require but only when not covering protocol supported elsewhere: ie. we don't intend to rewrite existing generator such as those supported by openapi)

**Comment by hezhiye** [comment]
ok, thank you very much.
i am looking for a tool for converting ARXML to franca, but none is existed except  franca_ara_tools.
however, franca_ara_tools need an AUTOSAR member for downloading artop package.
